language: rust
rust:
  - 1.37.0
  - stable
  - beta
  - nightly
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc
  - rustup component add rustfmt
  - cargo +nightly fmt -- --check
env:
  - QUICKCHECK_GENERATOR_SIZE=50 QUICKCHECK_TESTS=1000

matrix:
  allow_failures:
    - rust: nightly