language: rust
rust:
  - 1.37.0
  - stable
  - beta
  - nightly
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc
env:
  - QUICKCHECK_GENERATOR_SIZE=10 QUICKCHECK_TESTS=25
  - QUICKCHECK_GENERATOR_SIZE=50
  
matrix:
  allow_failures:
    - rust: nightly