[package]
name = "graphene"
version = "0.1.5"
authors = ["Emad Jacob Maroun <emoun.open@gmail.com>"]

description = "A general purpose, extensible Graph Theory data type and algorithm library for Rust."

license = "MIT"
readme = "README.md"

repository = "https://github.com/Emoun/graphene"

keywords = ["graph","algorithm"]
categories = ["data-structures","algorithms"]

[badges]

travis-ci = {repository = "Emoun/graphene"}

[dependencies]

[dev-dependencies]
quickcheck = "0.6"

